name: Cargo Publish

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Publish
      run: cargo publish --token {{ SECRETS.CARGO_TOKEN }}
